#!/usr/bin/env python
# encoding: utf-8

import os, sys, optparse, glob
import logging
from make_SDS_data_links import make_SDS_data_links

p=optparse.OptionParser()

p.add_option('--datadir',action='store',help="data directory")
p.add_option('--dataglob',action='store',help="data glob")
p.add_option('--outdir',action='store',help="output directory")
p.add_option('--debug',action='store_true',help="turn on debugging output")

(options,arguments)=p.parse_args()

if options.debug:
  logging.basicConfig(level=logging.DEBUG, format='%(levelname)s : %(asctime)s : %(message)s')
else:
  logging.basicConfig(level=logging.INFO, format='%(levelname)s : %(asctime)s : %(message)s')

make_SDS_data_links(options.datadir,options.dataglob,options.outdir)

